
import type { Product } from '@/lib/types';

export let allProducts: Product[] = [
  { id: '1', name: 'Premium Wireless Headphones', price: 570000, originalPrice: 760000, rating: 4.8, reviewCount: 2450, imageUrl: 'https://images.unsplash.com/photo-1585298723682-7115561c51b7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8aGVhZHBob25lc3xlbnwwfHx8fDE3NTA2Njk0MDB8MA&ixlib=rb-4.1.0&q=80&w=1080', dataAiHint: 'headphones music', description: 'Experience immersive sound with these noise-cancelling wireless headphones. Long-lasting battery and crystal-clear audio for music and calls.', category: 'electronics', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: '2', name: 'Smart Fitness Tracker Watch', price: 342000, rating: 4.6, reviewCount: 1890, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'smartwatch fitness', description: 'Track your fitness goals with this sleek and stylish smartwatch. Monitors heart rate, steps, and sleep patterns, all on your wrist.', category: 'electronics', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: '3', name: 'Professional DSLR Camera', price: 3416000, rating: 4.9, reviewCount: 980, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'camera photography', description: 'Capture stunning, high-resolution photos with this professional-grade DSLR camera. Perfect for both hobbyists and seasoned photographers.', category: 'electronics', status: 'Out of Stock', sellerName: 'YUNI Store' },
  { id: '4', name: 'Organic Green Tea Set', price: 114000, originalPrice: 152000, rating: 4.7, reviewCount: 3120, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'tea set', description: 'A curated selection of premium organic green teas. This set includes a variety of flavors, perfect for any tea lover.', category: 'beverages', status: 'In Stock', sellerName: 'Sofia Davis' },
  { id: '5', name: 'Modern Scandinavian Sofa', price: 4940000, rating: 4.8, reviewCount: 450, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'sofa furniture', description: 'Add a touch of minimalist elegance to your living room with this comfortable and stylish Scandinavian sofa. Built with high-quality materials.', category: 'home-office', status: 'In Stock', sellerName: 'Jane Smith' },
  { id: '6', name: 'Ultra-Light Running Shoes', price: 456000, rating: 4.5, reviewCount: 2200, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'running shoes', description: 'Feel like you are running on clouds with these ultra-light and responsive running shoes. Designed for maximum comfort and performance.', category: 'fashion', status: 'Archived', sellerName: 'YUNI Store' },
  { id: '7', name: '4K Ultra-HD Drone', price: 1900000, rating: 4.7, reviewCount: 150, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'drone camera', isNew: true, description: 'Capture breathtaking aerial footage in stunning 4K resolution. This easy-to-fly drone is perfect for capturing your adventures from a new perspective.', category: 'electronics', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: '8', name: 'Aesthetic Ceramic Vase', price: 171000, rating: 4.9, reviewCount: 210, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'vase decor', isNew: true, description: 'A beautiful, handcrafted ceramic vase to elevate your home decor. Its minimalist design complements any interior style.', category: 'home-office', status: 'In Stock', sellerName: 'Jane Smith' },
  { id: '9', name: 'Portable Espresso Maker', price: 249000, rating: 4.6, reviewCount: 340, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'coffee espresso', isNew: true, description: 'Enjoy delicious espresso anywhere, anytime. This compact and lightweight portable espresso maker is your perfect travel companion.', category: 'home-office', status: 'In Stock', sellerName: 'Sofia Davis' },
  { id: '10', name: 'Smart Garden System', price: 760000, originalPrice: 950000, rating: 4.8, reviewCount: 180, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'smart garden', isNew: true, description: 'Grow fresh herbs and vegetables indoors with ease. This smart garden system automates watering and lighting for a perfect harvest every time.', category: 'home-office', status: 'In Stock', sellerName: 'Jane Smith' },
  { id: '11', name: 'Vintage Leather Backpack', price: 361000, rating: 4.7, reviewCount: 412, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'backpack leather', isNew: true, description: 'A stylish and durable vintage leather backpack that combines classic design with modern functionality. Perfect for work, travel, or school.', category: 'fashion', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: '12', name: 'Augmented Reality Glasses', price: 3036000, rating: 4.5, reviewCount: 95, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'ar glasses', isNew: true, description: 'Step into the future with these cutting-edge augmented reality glasses. Overlay digital information onto the real world for a new way to interact with your environment.', category: 'electronics', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'fs1', name: 'Smart Air Fryer Pro', price: 342000, originalPrice: 494000, rating: 4.7, reviewCount: 1500, imageUrl: 'https://images.unsplash.com/photo-1714581069109-c5631e17eb00?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxhaXIlMjBmcnllcnxlbnwwfHx8fDE3NTA4MTEyNDl8MA&ixlib=rb-4.1.0&q=80&w=1080', dataAiHint: 'air fryer', description: 'Cook healthier meals with less oil. This smart air fryer features multiple cooking presets and can be controlled from your smartphone.', category: 'home-office', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'fs2', name: 'Noise-Cancelling Earbuds', price: 228000, originalPrice: 380000, rating: 4.5, reviewCount: 2300, imageUrl: 'https://images.unsplash.com/photo-1620360642994-974f7fd8e9b4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxlYXJidWRzJTIwYXVkaW98ZW58MHx8fHwxNzUwODExMjQ5fDA&ixlib=rb-4.1.0&q=80&w=1080', dataAiHint: 'earbuds audio', description: 'Immerse yourself in your music with these true wireless noise-cancelling earbuds. Compact design with a long-lasting battery.', category: 'electronics', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'fs3', name: 'Robotic Vacuum Cleaner', price: 760000, originalPrice: 1140000, rating: 4.8, reviewCount: 890, imageUrl: 'https://images.unsplash.com/photo-1731985997058-130b8703b8e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHx2YWN1dW0lMjByb2JvdHxlbnwwfHx8fDE3NTA4MTEyNTB8MA&ixlib=rb-4.1.0&q=80&w=1080', dataAiHint: 'vacuum robot', description: 'Keep your floors clean without lifting a finger. This robotic vacuum navigates your home intelligently, picking up dust and debris.', category: 'home-office', status: 'In Stock', sellerName: 'Jane Smith' },
  { id: 'fs4', name: 'Portable Power Bank 20000mAh', price: 114000, originalPrice: 190000, rating: 4.6, reviewCount: 5400, imageUrl: 'https://images.unsplash.com/photo-1644571663498-f4f18db66c17?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8cG93ZXIlMjBiYW5rfGVufDB8fHx8MTc1MDgxMTI1MHww&ixlib=rb-4.1.0&q=80&w=1080', dataAiHint: 'power bank', description: 'Never run out of battery again. This high-capacity power bank can charge your devices multiple times on a single charge.', category: 'electronics', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'fs5', name: 'Electric Standing Desk', price: 950000, originalPrice: 1330000, rating: 4.9, reviewCount: 650, imageUrl: 'https://images.unsplash.com/photo-1622131243631-1cf9ff4a8b9e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxzdGFuZGluZyUyMGRlc2t8ZW58MHx8fHwxNzUwODExMjUwfDA&ixlib=rb-4.1.0&q=80&w=1080', dataAiHint: 'standing desk', description: 'Switch between sitting and standing effortlessly with this electric adjustable desk. Improve your posture and productivity.', category: 'home-office', status: 'In Stock', sellerName: 'Jane Smith' },
  { id: 'fs6', name: 'Yoga Mat and Block Set', price: 133000, originalPrice: 228000, rating: 4.7, reviewCount: 1200, imageUrl: 'https://images.unsplash.com/photo-1600881333168-2ef49b341f30?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8eW9nYSUyMG1hdHxlbnwwfHx8fDE3NTA4MTEyNTB8MA&ixlib=rb-4.1.0&q=80&w=1080', dataAiHint: 'yoga mat', description: 'Everything you need for your yoga practice. This set includes a high-quality, non-slip yoga mat and two supportive foam blocks.', category: 'health', status: 'In Stock', sellerName: 'Sofia Davis' },
  { id: 'lp1', name: 'Hand-woven Area Rug', price: 874000, rating: 4.8, reviewCount: 210, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'rug home', description: 'Add warmth and style to any room with this beautifully hand-woven area rug. Made from natural fibers for a soft and durable finish.', category: 'home-office', status: 'In Stock', sellerName: 'Jane Smith' },
  { id: 'lp2', name: 'Gourmet Coffee Bean Sampler', price: 171000, rating: 4.9, reviewCount: 850, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'coffee beans', description: 'Explore a world of flavor with this gourmet coffee bean sampler. Features beans from three different renowned coffee-growing regions.', category: 'beverages', status: 'In Stock', sellerName: 'Sofia Davis' },
  { id: 'lp3', name: 'Smart LED Light Strip', price: 152000, rating: 4.6, reviewCount: 1800, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'led lights', description: 'Transform your space with customizable lighting. This smart LED strip offers millions of colors and can be synced with music.', category: 'electronics', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'lp4', name: 'Professional Chef\'s Knife', price: 456000, originalPrice: 570000, rating: 4.9, reviewCount: 1100, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'chef knife', description: 'A high-carbon stainless steel chef\'s knife that is a must-have for any kitchen. Perfectly balanced for precision and control.', category: 'home-office', status: 'In Stock', sellerName: 'Sofia Davis' },
  { id: 'lp5', name: 'Silk Pillowcase Set', price: 209000, rating: 4.7, reviewCount: 950, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'silk pillowcase', description: 'Experience the luxury of sleeping on pure silk. These pillowcases are gentle on your skin and hair, reducing friction and bedhead.', category: 'beauty', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'lp6', name: 'Wireless Charging Stand', price: 190000, rating: 4.6, reviewCount: 2200, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'charging stand', description: 'Charge your phone and other compatible devices wirelessly. This sleek stand supports fast charging and looks great on any desk or nightstand.', category: 'electronics', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'lp7', name: 'Insulated Water Bottle', price: 95000, rating: 4.8, reviewCount: 6500, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'water bottle', description: 'Keep your drinks cold for 24 hours or hot for 12. This stainless steel insulated water bottle is perfect for your active lifestyle.', category: 'home-office', status: 'In Stock', sellerName: 'Jane Smith' },
  { id: 'lp8', name: 'Hardcover Fiction Bestseller', price: 72000, rating: 4.9, reviewCount: 3200, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'book fiction', description: 'Get lost in the latest bestselling fiction novel that everyone is talking about. A captivating story from a critically acclaimed author.', category: 'books', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'g1', name: 'Fresh Apples (1kg)', price: 15000, rating: 4.5, reviewCount: 150, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'apples fruit', description: 'Crisp and sweet red apples, perfect for a healthy snack.', category: 'groceries', status: 'In Stock', sellerName: 'Sofia Davis' },
  { id: 'g2', name: 'Whole Wheat Bread', price: 8000, rating: 4.6, reviewCount: 200, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'bread loaf', description: 'Freshly baked whole wheat bread, rich in fiber.', category: 'groceries', status: 'In Stock', sellerName: 'Sofia Davis' },
  { id: 'g3', name: 'Organic Eggs (Dozen)', price: 12000, rating: 4.8, reviewCount: 300, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'eggs carton', description: 'Farm-fresh organic eggs, packed with protein.', category: 'groceries', status: 'In Stock', sellerName: 'Sofia Davis' },
  { id: 'g4', name: 'Cheddar Cheese Block', price: 25000, rating: 4.7, reviewCount: 180, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'cheese block', description: 'A rich and creamy block of cheddar cheese.', category: 'groceries', status: 'In Stock', sellerName: 'Sofia Davis' },
  { id: 'g5', name: 'Pasta (500g)', price: 7000, rating: 4.5, reviewCount: 400, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'pasta uncooked', description: 'Classic Italian pasta, perfect for your favorite sauces.', category: 'groceries', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'g6', name: 'Tomatoes (1kg)', price: 5000, rating: 4.6, reviewCount: 120, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'tomatoes vegetable', description: 'Fresh, juicy tomatoes for salads and cooking.', category: 'groceries', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'b1', name: 'Fanta Orange (500ml)', price: 2500, rating: 4.7, reviewCount: 1200, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'fanta soda', description: 'Bubbly and refreshing orange-flavored soda.', category: 'beverages', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'b2', name: 'Minute Maid Juice (1L)', price: 7000, rating: 4.6, reviewCount: 800, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'juice bottle', description: 'Delicious and pulpy orange juice.', category: 'beverages', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'b3', name: 'Riham Rock Boom', price: 3000, rating: 4.8, reviewCount: 2500, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'energy drink', description: 'Get a boost of energy with this popular energy drink.', category: 'beverages', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'b4', name: 'Mineral Water (1.5L)', price: 2000, rating: 4.9, reviewCount: 3000, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'water bottle', description: 'Pure and refreshing mineral water.', category: 'beverages', status: 'In Stock', sellerName: 'YUNI Store' },
  { id: 'b5', name: 'Mirinda Fruity (500ml)', price: 2500, rating: 4.6, reviewCount: 900, imageUrl: 'https://placehold.co/300x300.png', dataAiHint: 'mirinda soda', description: 'A burst of fruity flavor in a bottle.', category: 'beverages', status: 'In Stock', sellerName: 'YUNI Store' },
];

export const getTopSellingProducts = () => allProducts.filter(p => p.status !== 'Archived').slice(0, 6);
export const getNewArrivals = () => allProducts.filter(p => p.isNew && p.status !== 'Archived').slice(0, 6);
export const getLatestProducts = () => allProducts.filter(p => p.status !== 'Archived').slice(0, 8);
export const getGroceryProducts = () => allProducts.filter(p => p.category === 'groceries' && p.status !== 'Archived').slice(0, 6);
export const getBeverageProducts = () => allProducts.filter(p => p.category === 'beverages' && p.status !== 'Archived').slice(0, 6);

export function getProductById(id: string): Product | undefined {
  return allProducts.find((product) => product.id === id);
}

export function getProductsByCategory(category: string): Product[] {
  return allProducts.filter((product) => product.category === category && product.status !== 'Archived');
}
